---
- name:    Download Kubectl binary
  get_url:
    dest:  /tmp/kubectl
    url:   "https://storage.googleapis.com/kubernetes-release/release/v1.24.0/bin/linux/amd64/kubectl"

- name:         Copy kubectl to path
  become:       yes
  copy:
    src:        /tmp/kubectl
    dest:       /usr/local/bin/kubectl
    owner:      ubuntu
    group:      ubuntu
    mode:       '0775'
    remote_src: yes
...