---
version: 2.1

orbs:
  slack: circleci/slack@4.10.1

anchors:
  job-in-progress: &job-in-progress
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - run:
          name: TODO Message
          command: echo "Job is in progress"

commands:
  ubuntu-install-pip3:
    description: "Install pip3 onto image"
    steps:
      - run:
          name: Get Python3 Version
          command: python3 --version
      - run:
          name: Update apt
          command: sudo apt update
      - run:
          name: Install pip3
          command: sudo apt install python3-pip
      - run:
          name: Get pip3 version
          command: pip3 --version
  slack-fail-notification:
    description: "Slack Failure Notification"
    steps:
      - slack/notify:
          event: fail
          mentions: '@Johnny'
          template: basic_fail_1

jobs:
  lint-ansible:
    description: |
      Lint Ansible Playbooks under Project Path: .ansible/
    docker:
      - image: cimg/base:current-22.04
    steps:
      - checkout
      - run:
          name: Install Ansible Linter
          command: sudo make install-lint-ansible
      - run:
          name: Run Ansible Linter
          command: sudo make lint-ansible
      - slack-fail-notification

  lint-bash:
    description: |
      Lint Bash shell scripts in entire project directory
    docker:
      - image: cimg/base:current-22.04
    steps:
      - checkout
      - run:
          name: Install Bash Linter - Shell Check
          command: sudo make install-lint-bash
      - run:
          name: Run Shell Check Linter
          command: sudo make lint-bash
      - slack-fail-notification


  lint-circleci:
    description: |
      Lint CircleCI scripts in .circleci directory
    docker:
      - image: cimg/base:current-22.04
    steps:
      - checkout
      - run:
          name: Install CircleCI Linter - YAML Check
          command: sudo make install-lint-circleci
      - run:
          name: Run YAML Check
          command: sudo make lint-circleci
      - slack-fail-notification


  lint-docker:
    description: |
      Lint Dockerfiles in src/*/ directory
    docker:
      - image: cimg/base:current-22.04
    steps:
      - checkout
      - run:
          name: Install Hadolint
          command: sudo make install-lint-docker
      - run:
          name: Run Hadolint
          command: sudo make lint-docker
      - slack-fail-notification


  lint-groovy:
    description: |
      Lint Groovy scripts in .jenkins directory
    docker:
      - image: cimg/base:current-22.04
    steps:
      - checkout
      - run:
          name: Install Groovy Linter
          command: sudo make install-lint-groovy
      - run:
          name: Run Groovy Linter
          command: sudo make lint-groovy
      - slack-fail-notification


  lint-python:
    description: |
      Lint Python Code and Unit Tests
    docker:
      - image: cimg/base:current-22.04
    steps:
      - checkout
      - run:
          name: Install Python Linter - Pycodestyle
          command: sudo make install-lint-python
      - run:
          name: Run Pycodestyle
          command: sudo make lint-python
      - slack-fail-notification


  lint-tflint:
    description: |
      Lint Terraform Code
    docker:
      - image: cimg/base:current-22.04
    steps:
      - checkout
      - run:
          name: Install Terraform Linter - tflint
          command: sudo make install-lint-tflint
      - run:
          name: Run tflint
          command: sudo make lint-tflint
      - slack-fail-notification


  test-unit-scrape-api:
    description: |
      Unit Test Python Scrape API Applications
    docker:
      - image: cimg/base:current-22.04
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.11
      - run:
          name: Run Python Application - scrape-api
          command: |
            cd src/scrape-api/
            ./run_docker.sh
            cd ..
            cd ..
      - run:
          name: GET Unit Tests
          command: |
            sleep 15
            ssh remote-docker \ curl --fail 127.0.0.1:"$API_PORT"/
            ssh remote-docker \ curl --fail 127.0.0.1:"$API_PORT"/config
            ssh remote-docker \ curl --fail \
              127.0.0.1:"$API_PORT"/config-management
            ssh remote-docker \ curl --fail 127.0.0.1:"$API_PORT"/containers
            ssh remote-docker \ curl --fail 127.0.0.1:"$API_PORT"/health
      - slack-fail-notification


  test-unit-scrape-bot:
    description: |
      Unit Test Python Scrape Bot Applications
    docker:
      - image: cimg/base:current-22.04
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.11
      - run:
          name: Run Python Application - scrape-bot
          command: |
            cd src/scrape-bot/
            ./run_docker.sh
            cd ..
            cd ..
      - run:
          name: GET Unit Tests
          command: |
            sleep 15
            ssh remote-docker \ curl --fail 127.0.0.1:"$BOT_PORT"/
            ssh remote-docker \ curl --fail 127.0.0.1:"$BOT_PORT"/health
      - slack-fail-notification


  scan-scrape-api:
    <<: *job-in-progress


  scan-scrape-bot:
    <<: *job-in-progress


  test-integration:
    description: |
      Test Integration
    docker:
      - image: cimg/base:current-22.04
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.11
      - run:
          name: Run Python Application - scrape-api
          command: |
            cd src/scrape-api/
            ./run_docker.sh
            cd ..
            cd ..
      - run:
          name: Run Python Application - scrape-bot
          command: |
            cd src/scrape-bot/
            ./run_docker.sh
            cd ..
            cd ..
      - run:
          name: Integration Test
          command: |
            sleep 15
            ssh remote-docker \ curl --fail 127.0.0.1:"$API_PORT"/status
      - slack-fail-notification


  commit-docker:
    <<: *job-in-progress


  deploy-infrastructure:
    <<: *job-in-progress


  configure-infrastructure:
    <<: *job-in-progress


  run-migrations:
    <<: *job-in-progress


  deploy-scrape-api:
    <<: *job-in-progress


  deploy-scrape-bot:
    <<: *job-in-progress


  test-smoke:
    <<: *job-in-progress


  blue-green-switch:
    docker:
      - image: cimg/base:current-22.04
    steps:
      - run:
          name: TODO Message
          command: echo "Job is in progress"
      - slack/notify:
          event: pass
          template: basic_success_1


workflows:
  webscraper-devops-pipeline:
    jobs:
      ## - github-super-linter/lint
      - lint-ansible:
          context: slack-context
      - lint-bash:
          context: slack-context
      - lint-circleci:
          context: slack-context
      - lint-docker:
          context: slack-context
      - lint-groovy:
          context: slack-context
      - lint-python:
          context: slack-context
      - lint-tflint:
          context: slack-context
      - test-unit-scrape-api:
          context: slack-context
          requires:
            - lint-ansible
            - lint-bash
            - lint-circleci
            - lint-docker
            - lint-groovy
            - lint-python
            - lint-tflint
      - test-unit-scrape-bot:
          context: slack-context
          requires:
            - lint-ansible
            - lint-bash
            - lint-circleci
            - lint-docker
            - lint-groovy
            - lint-python
            - lint-tflint
      - scan-scrape-api:
          context: slack-context
          requires:
            - lint-ansible
            - lint-bash
            - lint-circleci
            - lint-docker
            - lint-groovy
            - lint-python
            - lint-tflint
      - scan-scrape-bot:
          context: slack-context
          requires:
            - lint-ansible
            - lint-bash
            - lint-circleci
            - lint-docker
            - lint-groovy
            - lint-python
            - lint-tflint
      - test-integration:
          context: slack-context
          requires:
            - test-unit-scrape-bot
            - test-unit-scrape-api
            - scan-scrape-bot
            - scan-scrape-api
      - commit-docker:
          context: slack-context
          requires:
            - test-integration
          filters:
            branches:
              only:
                - main
      - deploy-infrastructure:
          context: slack-context
          requires:
            - commit-docker
      - configure-infrastructure:
          context: slack-context
          requires:
            - deploy-infrastructure
      - run-migrations:
          context: slack-context
          requires:
            - configure-infrastructure
      - deploy-scrape-api:
          context: slack-context
          requires:
            - run-migrations
      - deploy-scrape-bot:
          context: slack-context
          requires:
            - run-migrations
      - test-smoke:
          context: slack-context
          requires:
            - deploy-scrape-api
            - deploy-scrape-bot
      - blue-green-switch:
          context: slack-context
          requires:
            - test-smoke

...
