---
version: 2.1

orbs:
  github-super-linter: circleci/github-super-linter@1.0

jobs:
  lint-ansible:
    description: |
      Lint Ansible Playbooks under Project Path: .ansible/
    docker:
      - image: cimg/base:current-22.04
    steps:
      - checkout
      - run:
          name: Install Ansible Linter
          command: sudo make install-lint-ansible
      - run:
          name: Run Ansible Linter
          command: sudo make lint-ansible
  
  lint-bash:
    description: |
      Lint Bash shell scripts in entire project directory
    docker:
      - image: cimg/base:current-22.04
    steps:
      - checkout
      - run:
          name: Install Bash Linter - Shell Check
          command: sudo make install-lint-bash
      - run:
          name: Run Shell Check Linter
          command: sudo make lint-bash

  lint-circleci:
    description: |
      Lint CircleCI scripts in .circleci directory
    docker:
      - image: cimg/base:current-22.04
    steps:
      - checkout
      - run:
          name: Install CircleCI Linter - YAML Check
          command: sudo make install-lint-circleci
      - run:
          name: Run YAML Check
          command: sudo make lint-circleci
  
  lint-docker:
    description: |
      Lint Dockerfiles in src/*/ directory
    docker:
      - image: cimg/base:current-22.04
    steps:
      - checkout
      - run:
          name: Install Hadolint
          command: sudo make install-lint-docker
      - run:
          name: Run Hadolint
          command: sudo make lint-docker
  
  lint-groovy:
    description: |
      Lint Groovy scripts in .jenkins directory
    docker:
      - image: cimg/base:current-22.04
    steps:
      - checkout
      - run:
          name: Install Groovy Linter
          command: sudo make install-lint-groovy
      - run:
          name: Run Groovy Linter
          command: sudo make lint-groovy
  
  lint-python:
    description: |
      Lint Python Code and Unit Tests
    docker:
      - image: cimg/base:current-22.04
    steps:
      - checkout
      - run:
          name: Install Python Linter - Pycodestyle
          command: sudo make install-lint-python
      - run:
          name: Run Pycodestyle
          command: sudo make lint-python
  
  lint-tflint:
    description: |
      Lint Terraform Code
    docker:
      - image: cimg/base:current-22.04
    steps:
      - checkout
      - run:
          name: Install Terraform Linter - tflint
          command: sudo make install-lint-tflint
      - run:
          name: Run tflint
          command: sudo make lint-pyttflinthon

workflows:
  webscraper-devops-pipeline:
    jobs:
      # - github-super-linter/lint
      - lint-ansible
      - lint-bash
      - lint-circleci
      - lint-docker
      - lint-groovy
      - lint-python
      - lint-tflint
...