# OUTPUTS FROM STATE FILE

/*
# RESOURCE OUTPUT
output "OUTPUT_VARIABLE" {
  description = "OUTPUT_DESCRIPTION"
  value       = RESOURCE_TYPE.RESOURCE_NAME.ATTRIBUTE_USED
}

# VARIABLE OUTPUT
output "OUTPUT_VARIABLE" {
  description = "OUTPUT_DESCRIPTION"
  value       = var.VARIABLE
}
*/
